// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/baoshuyan/Documents/bai/bai-design-react/node_modules/dumi/theme-default/builtins/API/index.js';
