name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run deploy:site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./doc-site
      - run: npm run semantic-release
